[package]
name = "topkio-ollama"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
reqwest.workspace = true
serde_json.workspace = true
topkio-primitive ={ path = "../../primitive"}
async-trait.workspace = true
anyhow.workspace = true